# Generated by Django 5.0.2 on 2024-03-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notification_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
