# Generated by Django 5.0.2 on 2024-03-08 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_tag_remove_membershiptype_band_blog_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
